title: 9Log
email: khgkjg12@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  개발자 강현구의 컴퓨터 공학 및 프로그래밍 지식 저장소
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://rkdgusrn1212.github.io/' # the base hostname & protocol for your site, e.g. http://example.com
github_username: rkdgusrn1212

plugins:
  - jekyll-feed

source: build
